-- Hyprland colors generated by Matugen
-- Source wallpaper: {{image}}

hl.config({
  general = {
    col = {
      active_border = "rgba({{colors.outline.default.hex_stripped}}ff)",
      inactive_border = "rgba({{colors.outline_variant.default.hex_stripped}}ff)",
    },
  },
})
